development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: blogger 
  password: blogger
test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: blogger 
  password: blogger
production:
  adapter: postgresql
  encoding: unicode
  database: myapp_production
  pool: 5
  username: blogger 
  password: blogger